package HelloWorldApp;


/**
* HelloWorldApp/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorld.idl
* Sunday, November 2, 2025 3:08:49 PM WEST
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
